Repository hashicorp/vagrant, pull requests merged in 2018-09, with the labels that each got.

#10182 Check verify_host_key for falsey or :never values when generating ssh config
  templates/commands/ssh_config/config.erb
  test/unit/plugins/commands/ssh_config/command_test.rb
Labels: pr/ready-for-merge

#10171 vagrant init: Support VAGRANT_DEFAULT_TEMPLATE
  plugins/commands/init/command.rb
  test/unit/plugins/commands/init/command_test.rb
  website/source/docs/other/environmental-variables.html.md
Labels: pr/needs-review

#10168 bash: complete running VM names for destroy subcommand
  contrib/bash/completion.sh
Labels: pr/needs-review

#9054 Add completion for snapshot names for vagrant snapshot restore|delete
  contrib/bash/completion.sh
Labels: pr/needs-review

#10219 Allow special characters in SMB password field
  plugins/guests/windows/cap/mount_shared_folder.rb
  test/unit/plugins/guests/windows/cap/mount_shared_folder_test.rb
Labels: guest/windows, synced-folders/smb

#10221 Docker provider build from repo
  plugins/providers/docker/action/build.rb
  plugins/providers/docker/action/is_build.rb
  plugins/providers/docker/config.rb
  templates/locales/providers_docker.yml
  test/unit/plugins/providers/docker/config_test.rb
  website/source/docs/docker/configuration.html.md
Labels: enhancement, provider/docker
