Repository hashicorp/vagrant, pull requests merged in 2018-07, with the labels that each got.

#9966 Added option to add to User-Agent
  lib/vagrant/util/downloader.rb
  website/source/docs/other/environmental-variables.html.md
Labels: pr/reviewed

#9889 Increase priority and support multiple networks for Debian with systemd-networkd
  plugins/guests/debian/cap/configure_networks.rb
  test/unit/plugins/guests/debian/cap/configure_networks_test.rb
Labels: guest/debian, networking

#9987 contrib/bash/completion.sh: replaced -VAGRANTSLASH- with a literal sl…
  contrib/bash/completion.sh
Labels: pr/needs-review
